FROM node:20.12-alpine as builder

RUN apk update && apk add bash
RUN apk update && apk add curl

ENV API_URL=http://backend:8080

WORKDIR /usr/src/app

COPY . .

RUN yarn install

RUN yarn build

CMD ["yarn", "start"]