version: "3"
services:
  node:
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
      - "./scripts/create_database.sql:/docker-entrypoint-initdb.d/create_database.sql"
    environment:
      MYSQL_ROOT_PASSWORD: root
volumes:
  db-data: {}
